spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: order-service
          uri: http://order-service:8081
          predicates:
            - Path=/api/orders/**
        - id: kitchen-service
          uri: http://kitchen-service:8082
          predicates:
            - Path=/api/kitchen/**
        - id: waiter-service
          uri: http://waiter-service:8083
          predicates:
            - Path=/api/waiter/**